name: Build with MSBuild and vcpkg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          ./vcpkg/vcpkg install fmt

      - name: Build with MSBuild
        run: |
          msbuild YourProject.sln /p:Configuration=Release
