name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: vcpkg
          runVcpkgInstall: true
          runVcpkgFormatString: >-
            [`install`,`--recurse`,`--clean-after-build`,
             `--triplet`,`x64-windows`,
             `--x-manifest-root`,`$[env.GITHUB_WORKSPACE]`]
          doNotCache: false

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
        
      - name: Build solution
        run: msbuild CarEdger.sln /m /p:Configuration=Release /p:Platform=x64      
