name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install vcpkg dependencies
        run: |
          .\vcpkg\vcpkg.exe install --triplet x64-windows --x-manifest-root %CD%

      - name: Build solution
        run: msbuild CarEdger.sln /m /p:Configuration=Release /p:Platform=x64
